-- AlterTable
ALTER TABLE `jr_projects` ADD COLUMN `start_date` DATETIME(3) NULL AFTER `extended`;
ALTER TABLE `jr_projects` ADD COLUMN `end_date` DATETIME(3) NULL AFTER `start_date`;

-- Insert Categories
INSERT INTO `jr_cats` (`title`, `created_at`, `updated_at`) VALUES
('Featured Projects', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Projects', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Work History', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

-- Insert Skills
INSERT INTO `jr_skills` (`name`, `desc`, `rating`, `created_at`, `updated_at`) VALUES
('JSON', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('HTML5 Canvas', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('JavaScript Libraries', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('GitHub Copilot', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Application Development', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('System Architecture', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Chrome Extension Development', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Frontend Web Development', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Backend Web Development', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Mobile Application Development', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Twilio Integration', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Chrome Extension Management', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Amazon S3', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Amazon Web Services (AWS)', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Amazon SQS', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('HTML Emails', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Email Marketing', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Twilio', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Iframes', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Customer Relationship Management (CRM)', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Lead Generation', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Marketing Campaign Management', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Cron', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Zend', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Elasticsearch', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ZURB Foundation Framework', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Twig (Template Engine)', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('User Interface Design', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Document Object Model (DOM)', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Android Studio', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Android SDK', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('API Development', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('REST APIs', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Scraping', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Data Entry', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Databases', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Laravel Lumen', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Vue.js', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Vuetify', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('HTML5', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Back-End Web Development', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Wordpress Development', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('WordPress Design', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('FTP', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Server Administration', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Genesis Framework for WordPress', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Responsive Web Design', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('PSD to HTML', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Confluence', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Jira', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('SASS', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Node.js', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('GitHub', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Chrome Extensions', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Team Lead', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Laravel', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Nuxt.js', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('HTML', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('CSS', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('JavaScript', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('jQuery', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('XHTML', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('XML', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('PHP', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('phpMyAdmin', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('MySQL', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('SQL', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('SQL Server', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('AJAX', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Java', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Ruby', '', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Curl', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Database Design', '', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Wordpress', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('PSD to Wordpress', '', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Joomla', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('PSD to Joomla', '', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

-- Insert Projects
INSERT INTO `jr_projects` (`name`, `short`, `role`, `position`, `start_date`, `end_date`, `extended`, `created_at`, `updated_at`) VALUES
('JR Programming', 'Portfolio website built with Next.js, Tailwind, and Prisma.', 'Web Developer', 'JR Programming', NULL, NULL, 'I used Github Copilot to assist me in creating this portfolio website in React.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Sands Investment Group', 'Delivered script to generate PDF file of Listings downloaded from the website.', 'Wordpress Web Developer', 'Freelancer', '2014-07-01 00:00:00.000', '2015-03-01 00:00:00.000', 'I was originally hired to create a script that would generate a PDF file of Listings downloaded from the website. This was completed successfully, but I was then later asked to help complete the website as the client''s original programmer left the project.  Originally I simply made improvements to the site by allowing the user listing to be easily updated and tweaking various pages, but later they hired a designer to redesign parts of the site, and I made sure my implementations were still working during this process.  Eventually, the client decided to go with an entirely new theme. Because of this, I had to completely rewrite the Listing page''s scripts manually, instead of using the custom plugin their previous programmer had before.  I recreated the plugin features using skills I had learned from working with a different client. The Listings page uses jQuery to load new data via AJAX and insert it onto the page. As you toggle the various search settings the listings are constantly revising the list. In addition, as you scroll down more listings will load automatically, which is a feature I''m very proud of.  Later I was asked to improve the process of downloading files on individual listings. I took the plugin that I used originally and completely rewrote it to improve the listings in the backend and add more features to export contacts.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Real Chords Website', 'PSD to Wordpress website design for a Mobile App.', 'Wordpress Web Developer', 'Appster', '2013-09-01 00:00:00.000', '2014-09-01 00:00:00.000', 'Real Chords is an app for iPhone with a companion app, Real Chords Pro, for iPad. Appster developed the Real Chords app for a client and hired me to handle development of the website, based on Wordpress. The website was built up from a PSD using my wrapper Wordpress theme jrBlog as the basis. There are four main pages, the homepage, separate iPhone and iPad manuals, and also the Blog page. The manuals had specific styling to line up all the text properly on each example, while the homepage used jQuery for the image and video galleries.  Support for RealChords ended in 2020 and I shut down the website as requested.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Millennium Marketing Denver Updates', 'Configured contact forms and styled them, added Connect With Us in footer, performed other enhancements.', 'Web Developer', 'Freelancer', '2013-09-01 00:00:00.000', '2013-09-01 00:00:00.000', 'On the Millennium Marketing website I did a number of enhancements. I added in all the contact forms and styled them. I added the Connect With Us! section in the footer. I updated the copyrights in the footer to the. I also updated the images on other pages, in some cases moving the images from the sidebar into the content, and I created the Reputation Marketing and Contact Us pages. I created all of these updates by creating a plugin to update the content in Genesis Framework.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Express Roofing, Inc.', 'PSD to Wordpress website design for SEO Strong.', 'Web Developer', 'SEO Strong', '2013-07-01 00:00:00.000', '2013-07-01 00:00:00.000', 'Express Roofing is another website I did for SEO Strong, for the same company as Extreme Developers. Unlike Extreme Developers, though, Express Roofing was built from a PSD rather than an old website. Like Extreme Developers a lot of the content is widget-based and is separated into different pages using Dynamic Widgets.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Extreme Developers, Inc.', 'Flash to Wordpress website design for SEO Strong.', 'Wordpress Web Developer', 'SEO Strong', '2013-06-01 00:00:00.000', '2013-06-01 00:00:00.000', 'Extreme Developers, Inc. is a website I built for SEO Strong based on an old flash website. The layout and style is based mostly on the prior Extreme Dev website, converted from flash. Its all Wordpress, with the slider run on the Meta Slider plugin. Dynamic Widgets is used to control how widget content is differentiated on separate pages.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Abundance Campaign', 'Delivered Landing Page designs for Abundance.', 'Web Developer', 'Yazamo', '2013-05-01 00:00:00.000', '2013-06-01 00:00:00.000', 'I helped do some development work on Piranha Media''s Abundance Campaign for Yazamo. While I did not do the whole Abundance project, I did work on a number of landing pages for the Abundance campaign and did several variants. I also made quite a few pages on Abundance responsive as well.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Packard Grill', 'Delivered WordPress theme enhancements, design updates, and backend menu setup for the restaurant website.', 'Web Developer', 'Freelancer', '2013-05-01 00:00:00.000', '2013-05-01 00:00:00.000', 'Packard Grill is another website I developed for Dominate Net. Packard Grill is a bar and grill located in Detroit, MI and the website is based on the WP Adora theme. I created a child theme for WP Adora to make most of the design updates and enhancements on the website. I also ended up having to go through and fill out all the menus for the company in the backend.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('25kGroup Magazine Lander', 'Built Yellow Magazine landing pages from PSD, including homepage, order, thank-you, and content pages.', 'Web Developer', 'Freelancer', '2013-04-01 00:00:00.000', '2013-04-01 00:00:00.000', 'Another project I did for Yazamo and Piranha Media was the Yellow Magazine Landing Page. These landing pages were designed to be based on two magazines that provided information on the 25kGroup. I did the web pages for the Yellow version of the landing pages, which consists of the Homepage, Order Page, Thank You Page, and Content page. Additional pages were added later as well. As per usual I developed the pages based on a PSD provided.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('BioDental Veneers Landing Page', 'Built a complex PSD-to-web landing page for BioDental Veneers.', 'Web Developer', 'Freelancer', '2013-03-01 00:00:00.000', '2013-03-01 00:00:00.000', 'For SEO Strong I did quite a bit of work on the website here and there, but the Veneers Landing Page I did completely based on a PSD file. The layout was quite complicated and required specific styles to lay out each section.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Genius Network Mastermind', 'Finalized site updates, restyled Case Studies, and fixed dropdown and Resources page issues.', 'Web Developer', 'Freelancer', '2013-03-01 00:00:00.000', '2013-03-01 00:00:00.000', 'I finalized the Genius Network Mastermind website for Yazamo and Piranha Media. Parts of the designs were already done, but I made some fixes to the existing pages, and completing re-styled the Case Studies page. I also fixed the dropdowns and updated the Resources page. The site has since been completely revamped again.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Center for the Partially Sighted', 'Finalized site launch and delivered theme, footer, font changer, and homepage content fixes.', 'Web Developer', 'Freelancer', '2013-03-01 00:00:00.000', '2013-03-01 00:00:00.000', 'CPS, Center for the Partially Sighted, is a website that I finished up and finalized for KloutFire. I originally took the website from a dev site and transferred it to replace the old CPS website. I later went in and made additional fixes and updates to the website by fixing up the theme so that blog posts wouldn''t interfere with content on the homepage as the original designers of the theme didn''t do the best job of it.  I also fixed the Font changer, reorganized the content in the footer, and updated the content on other pages to be based on regular Wordpress pages instead of being directly placed in Page Templates as it had been before.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Mangat Plastic Surgery', 'Implemented a complex WordPress layout with custom widget-driven tabbed navigation near the logo.', 'Wordpress Web Developer', 'Freelancer', '2013-02-01 00:00:00.000', '2013-02-01 00:00:00.000', 'Mangat Plastic Surgery is another website I worked on for KloutFire. The website is quite detailed and contains some complex designs. One of the parts I''m most impressed by with this site is the setup of the tabs in front of the logo.  The tabs are separated into the images themselves and the links, which are both separate widget areas. The links are generated using a Custom Menu widget, and the images are a series of Image Widgets (using the "Image Widget" plugin).  The website has since been redesigned and does not contain any element that I previously worked on.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Joe Polish Press Page', 'I developed and finalized the Press Page for JoePolish.com for Yazamo. The page is Wordpress-based, designed using a Page Template and inserted post content.', 'Web Developer', 'Freelancer', '2013-02-01 00:00:00.000', '2013-02-01 00:00:00.000', 'I developed and finalized the Press Page for JoePolish.com for Yazamo. The page is Wordpress-based, designed using a Page Template and inserted post content.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Restyle Kitchen and Bath', 'Converted an existing ASP website to WordPress for easier long-term content management.', 'Wordpress Web Developer', 'Freelancer', '2013-01-01 00:00:00.000', '2013-01-01 00:00:00.000', 'I converted an ASP website to Wordpress called Restyle Kitchen and Bath for Lead Optimize. The website was already up online before, but by remaking it into a Wordpress website I enabled much of the content on the website to be more easily editable than it was before.  The website has since gone defunct.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('KloutFire Website', 'Built and configured the initial WordPress website for KloutFire.', 'Wordpress Web Developer', 'Kloutefire', '2013-01-01 00:00:00.000', '2013-01-01 00:00:00.000', 'I created the initial KloutFire website at the beginning of 2013. Unlike my prior projects for KloutFire, I did not finish an existing website but created the website using a Wordpress theme instead called November. I configured much of the initial website, but did not make many changes to the website over the next several months; the KloutFire staff primarily maintained the website themselves and I only stepped in to make minor fixes here and there.  Kloutfire appears to now be defunct.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('My Choice Energy', 'Delivered a redesign with complex automated registration and renewal form processing.', 'Web Developer', 'Freelancer', '2012-11-01 00:00:00.000', '2013-02-01 00:00:00.000', 'Easily the most complicated website I had to deal with for My Choice Energy, this website required was a redesign of an existing website but also contained a complex process to automatically submit client''s registrations and renewals automatically. The main website and initial form processes were completed in 2012, but I was later informed of additional processes that needed to be added to it later, which was finally fully completed in February 2013 due to other contractual obligations I had received while waiting for the final information on the website form processes required.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Tansavatdi Plastic Surgery', 'Finalized the initial site launch and continued delivering updates through 2013.', 'Web Developer', 'Freelancer', '2012-12-01 00:00:00.000', '2013-07-01 00:00:00.000', 'I finished off the initial Tansavatdi Plastic Surgery website for KloutFire late 2012. The basic site was already mostly done, but I put together the finishing touches and continued to make many additional updates to the website throughout the year.  The website has since mostly been completely redesigned.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Raffle Consulting', 'Finalized the site and delivered follow-up fixes and updates for the client.', 'Web Developer', 'Freelancer', '2012-11-01 00:00:00.000', '2012-11-01 00:00:00.000', 'I finished the website Raffle Consulting as my first project for KloutFire late 2012. I made many additional updates and fixes to the site as well, though I did not start the website myself.  The site layout was eventually completely changed and my work no longer appears to be present on the site.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Washington Dental', 'Converted a PSD into a custom WordPress site based on the TwentyTwelve theme.', 'Wordpress Web Developer', 'SEO Strong', '2012-10-01 00:00:00.000', '2012-10-01 00:00:00.000', 'Washington Dental is the first website I did for SEO Strong. The website was converted from a PSD to Wordpress and the theme was based on TwentyTwelve.  The theme I created is currently no longer in use.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Fort Collins Roofing Consultants', 'Built a custom WordPress theme and populated the full site with pages and images.', 'Wordpress Web Developer', 'Freelancer', '2012-10-01 00:00:00.000', '2012-10-01 00:00:00.000', 'Created a custom Wordpress Theme for a website, then added all the pages and images for the website. The theme was based on Wordpress'' Twenty Eleven theme with updates to the base layout and images.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('PeteMamos.com', 'Finalized homepage, archives, and core content pages before launching the site live.', 'Web Developer', 'Freelancer', '2012-09-01 00:00:00.000', '2012-09-01 00:00:00.000', 'I finalized the Pete Mamos, Stage Hypnotist website. I added in the homepage setup, created the archives, and filled in all the archives from the old website. I also made additional touch ups to the site and put the website up live. My work was primarily on the Home, Hypnosis, and Schedule pages, and finalizing these three pages was the finishing touches to the website.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Home Solution Properties', 'Built a custom PHP website and integrated Curl-based form submission to an external service.', 'Web Developer', 'Freelancer', '2011-05-01 00:00:00.000', '2011-05-01 00:00:00.000', 'Home Solution Properties is the first website I completed in its entirety for a client on oDesk. The design of the website was based on another website which I recreated. The website is built on a basic custom PHP layout rather than Wordpress.  Had I done the website a few months later, I would''ve made it Wordpress instead. It was also the first time I ever used Curl for anything. I created a script run on Curl to send the form data to a separate site.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Equilibrio Nicaragua', 'Added new pages, refreshed image styling, and updated the homepage slider.', 'Web Developer', 'Freelancer', '2011-09-01 00:00:00.000', '2011-11-01 00:00:00.000', 'Equilibrio Nicaragua is a website I worked on for a short few months. I did a lot of updates to the site during that time, though. I created several new pages, added rounded borders on all the website''s images, and updating the image slider.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Freight Access CRM', 'Built the original CodeIgniter CRM and gained foundational web application development experience.', 'Lead Developer', 'Freelancer', '2010-08-01 00:00:00.000', '2012-10-01 00:00:00.000', 'I created the original Freight Access CRM, built on Codeigniter framework, back in Fall 2010 as one of my earliest web development projects. The initial CRM was developed for a few months while I was still in college and I didn''t have full time to work on it. I continued to develop the CRM for some time and much of my months that don''t seem to have much work in them, I actually spent working on the FA CRM.  While I did work on it for some time, the scope of the project was just too big for me to handle, but it is where I got a lot of experience developing websites and web applications before I started getting other jobs though oDesk.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Craigslist Autoposter', 'Built a Chrome extension to automate Craigslist inventory posting with ongoing feature and paid-posting support.', 'Lead Developer', 'TrailerCentral', '2016-06-01 00:00:00.000', '2026-01-01 00:00:00.000', 'For Trailer Central''s Marketing product I wrote a new Craigslist Autoposter using a Google Chrome Extension.  This extension allows users with TrailerCentral Marketing to choose an inventory item from their dashboard and the extension will go out to craigslist, log into an account, start a new listing, and fill out all the details from their inventory item to sell it on Craigslist.  The script is designed to minimize manual data entry work while replicating a real user''s input.  Many updates have gradually been made over the years to fix issues, improve performance, and add additional functionality such as renews, syncing data, and eventually the shift to almost entirely paid posting only.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerTrader (2016 Version)', 'Migrated the first TrailerTrader draft, cleaned the UI, and connected the inventory database.', 'Fullstack Developer', 'TrailerCentral', '2016-04-01 00:00:00.000', '2016-08-01 00:00:00.000', 'Migrated early draft of TrailerTrader from outsourced demo to trailertrader.com, cleaned up trailer trader markup and design, connected TrailerTrader to TrailerCentral inventory database.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Horse Trailer World Autoposter', 'Built a Chrome extension to sync dealer inventory into HorseTrailerWorld accounts.', 'Web Scrapers', 'TrailerCentral', '2016-04-01 00:00:00.000', '2026-01-01 00:00:00.000', 'Wrote an extension for Google Chrome to post dealer''s inventory from TrailerCentral to existing dealer accounts on HorseTrailerWorld. The script is designed to sync dealer data by logging into a dealer''s existing paid Horse Trailer World account and manually enter dealer data from TrailerCentral.  The purpose of this extension is to minimize lengthy data entry so dealers can share their inventory across as many platforms as possible.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral KSL Feed', 'Wrote an early version of the TrailerCentral KSL feed. This feed was handled mostly using PHP and CURL to read web page data like a more traditional scraper.', 'Web Scrapers', 'TrailerCentral', '2016-06-01 00:00:00.000', '2016-12-01 00:00:00.000', 'Wrote an early version of the TrailerCentral KSL feed. This feed was handled mostly using PHP and CURL to read web page data like a more traditional scraper.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Camera Mobile App', 'Maintained the Android camera app for inventory image download and upload workflows.', 'Mobile App Developer', 'TrailerCentral', '2016-08-01 00:00:00.000', '2023-06-01 00:00:00.000', 'I never worked on a mobile app before and finally got my chance with the TrailerCentral Camera app on Android. The app''s main purpose was to allow users to upload images via their mobile phone camera, likely while on the lot looking at inventory to sell online via TrailerCentral.  I played around with Android Studio to figure out how the app worked and make some improvements. With the Camera App users log into their trailer central account, received a list of inventory, downloaded all existing images, and could upload new images.  The app already existed when I started working on it, but I made some updates and maintained it, though I still had difficulty figuring out how to make major improvements as Android Studio/Java is not my best skill.  The app was somewhat maintained for many years until being replaced by the new TrailerCentral & CRM Dashboard app instead which I was not directly involved in.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Craigslist Scheduler (Chrome Extension)', 'Extended the Craigslist autoposter with scheduling and paid-posting support.', 'Web Scrapers', 'TrailerCentral', '2016-09-01 00:00:00.000', '2021-06-01 00:00:00.000', 'The TrailerCentral Craigslist Scheduler was built off of the original Craigslist Autoposter. With the Scheduler, the idea was to allow dealers to pick times to schedule inventory to post to Craigslist so they didn''t have to  constantly run the extension on their own PC and they didn''t have to worry about constantly going back and triggering a new set of posts to go out once the old ones finished.  To handle the schedular we installed a Javascript plugin called Full Calendar and used this to allow dealers to schedule posts. The main infrastructure remained the same as the standard poster, but now we added a scheduled date to all inventory.  However, around this time Craigslist also started charging for all By Dealer posts. As such, we had to implement some changes to enable paid posting on most inventory. While our system supports dealers posting as much to craigslist as they want, we expected dealers to pay for each individual paid listing.  The scheduler was originally built in the main CL Autoposter chrome extension, but we sunset that version.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Facebook Marketplace Autoposter', 'Built an early Chrome-based Facebook Marketplace autoposter and scheduling workflow.', 'Web Scrapers', 'TrailerCentral', '2016-09-01 00:00:00.000', '2017-06-01 00:00:00.000', 'The Facebook Marketplace poster was designed to work the same way as the Craigslist and HTW autoposters, though closer to CL. This autoposter was created as a chrome extension and was intended to be set up using a scheduler.  This was eventually dropped in favor of other methods until Marketplace shut down the ability for dealers to post content entirely.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Custom Inventory Image Overlays', 'Built an overlay system with banners, contact details, and logo placement for inventory images.', 'Web Developer', 'TrailerCentral', '2017-02-01 00:00:00.000', '2021-07-01 00:00:00.000', 'Wrote a custom image overlay system for TrailerCentral Dashboard to enable adding overlays to all dealer inventory. With this system we added a variety of new options for overlays, with the primary intention being to allow these settings to be used for dealer inventory going out to Craigslist posts.  This system enabled a banner at the top and bottom of each image to add a dealer name, phone, and/or contact email (two of each). We also added support for adding a logo to any corner of the image. The database saved a copy of the old image to ensure that we could still revert back to the original image should the dealer choose to disable the overlays.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Dealer Websites Responsive Mode', 'Enabled responsive dealer websites and introduced Twig template support for custom overrides.', 'Web Developer', 'TrailerCentral', '2017-03-01 00:00:00.000', '2019-05-01 00:00:00.000', 'Researched how the dealer websites configuration worked to enable Responsive designs for Dealer Websites. I configured the functionality for Responsive websites for our website design team in Dealer Websites, starting with Mayes Trailer Sales.  As part of this we configured a new functionality called Twig Templates as well to make custom designs and overrides easier for specific dealer websites.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Elastic Search for TrailerCentral Dealer Websites Inventory', 'Supported early Elasticsearch integration to improve dealer inventory search performance.', 'Web Developer', 'TrailerCentral', '2017-04-01 00:00:00.000', '2019-08-01 00:00:00.000', 'Worked on researching ElasticSearch implementation for Dealer Websites Inventory. Elasticsearch is used to improve loading speeds for specific types of data that requires high demand and consistent processing from the database.  For TrailerCentral''s Dealer Websites, ElasticSearch was implemented to improve the loading speeds of Inventory listings and not put too much of a burden on the primary database. I didn''t work too heavily on ElasticSearch but I did work on its early implementation.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Classifieds Websites', 'Supported the classifieds platform and an interim TrailerTrader implementation.', 'Web Developer', 'TrailerCentral', '2017-03-01 00:00:00.000', '2019-08-01 00:00:00.000', 'TrailerCentral''s Classifieds are similar to TrailerTrader where they handle specific types of content. This was also used as one version of TrailerTrader temporarily before it was shifted over to a new format in the future.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Factory Vantage', 'Added Series support and delivered admin and data updates for manufacturer and model workflows.', 'Web Developer', 'TrailerCentral', '2017-02-01 00:00:00.000', '2021-03-01 00:00:00.000', 'I worked on a number of additional features for Factory Vantage over the years, but mostly minor additions. I created the Series functionality to support including Series for RV''s, a classification level existing between that of Model and Manufacturer/Brand.  Most additions to Factory Vantage were primarily done via the database. However, I also supported it by updating the UI and forms in the admin interface. Factory Fantasy is also what controls autocompletion data for manufacturers / models on TrailerCentral Dashboard.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Huffman Trailers Website for TrailerCentral', 'Built a custom PSD-to-HTML/CSS dealer site with a homepage slideshow.', 'Web Developer', 'TrailerCentral', '2018-03-01 00:00:00.000', '2018-03-01 00:00:00.000', 'I created the original Huffman Trailers website for TrailerCentral Dealer Sites. This one required some custom functionality the design team wasn''t able to do at the time, so I did a new PSD to HTML/CSS website by ripping the images from the PSD preview and installing a slideshow for the home page.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('The Hitchman, Inc. Website for TrailerCentral', 'Rebuilt the dealer site in Foundation and added a custom Parts lookup with API and AJAX.', 'Web Developer', 'TrailerCentral', '2018-03-01 00:00:00.000', '2018-08-01 00:00:00.000', 'Hitchman, Inc. was a website that was migrated from another service to TrailerCentral. I was the lead on this one, rebuilding the website structure in Foundation on TrailerCentral''s Dealer Websites service.  This one also required me to create a custom Parts lookup system as well using an API and AJAX calls.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral CRM (Zend)', 'Expanded the Zend CRM with campaigns, messaging, and lead auto-assignment notifications.', 'Web Developer', 'TrailerCentral', '2018-04-01 00:00:00.000', '2025-06-01 00:00:00.000', 'The original TrailerCentral CRM was build in Zend Framework. I started working on it and it became a major project of mine. The original CRM was a separate interface from the main dashboard directly linked to a dealer''s main account if they opted in to the separate product.  Over time more features were added, including sending basic emails, sending texts, and also email and later text campaigns. While some basic functionality existed I wrote many of these new features myself. I also implemented an auto assign script to send email notifications to dealers so when new leads come in, dealers and sales people receive notifications.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral CRM Email & Text Marketing', 'Maintained campaign tooling with Mosaico, SES/SNS/SQS tracking, and NeverBounce checks.', 'Web Developer', 'TrailerCentral', '2018-05-01 00:00:00.000', '2026-01-01 00:00:00.000', 'The TrailerCentral CRM has a campaign and blast feature, complete with an Email Builder built onto Mosaico. I did not configure the original but I have maintained it over the years. The email building enables users to create custom email templates to send out in email campaigns and blasts for marketing to leads.  The campaign and blast functionality enables users to send campaigns out over a set period of time, or send out a single email to a bunch of leads who join within X amount of days. In addition, a text version of the campaign and blast functionality was also implemented, with text-only templates.  The system is built on Amazon Web Services'' Simple Email Service. SES, along with Simple Notification Service (SNS) and Simple Queue Service (SQS) enable us to track if the email will bounce, a complaint (spam) was reported, or if the email was delivered successfully and clicked or opened.  Very late in the lifespan of the feature we also added in support for checking if an email will bounce before ever attempting to send the email to begin with using NeverBounce.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral Facebook Marketplace Autoposter', 'Built a later Marketplace autoposter iteration before the workflow shifted to other solutions.', 'Web Developer', 'TrailerCentral', '2019-01-01 00:00:00.000', '2019-06-01 00:00:00.000', 'The TrailerCentral Facebook Marketplace autoposter was attempted several times but this one was a lot more complex to implement. I built the initial one very similarly to the HTW and Chrome Extensions. However, I kept struggling with triggering certain inputs such as uploading images.  We ended up having to hire a temp to come in and resolve this issue, but the problem we were unable to overcome is logging in and out of dealers, which required constant verifications. Because of this problem, we had to switch to a different system entirely.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral TruckPaper Autoposter Integration', 'Implemented an automated TruckPaper posting integration using XPath-driven browser workflows.', 'Web Developer', 'TrailerCentral', '2019-07-01 00:00:00.000', '2019-08-01 00:00:00.000', 'TruckPaper was another chrome extension autoposter designed to allow dealers to send inventory to another website for marketing purposes. The integration was configured and set to automatically run, using xpaths to log in and fill out form fields. While it was configured, it eventually stopped working and wasn''t deemed viable to keep active.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('TrailerCentral LotVantage Facebook Feed', 'Built a CSV feed integration to syndicate inventory to Facebook Marketplace through LotVantage.', 'Web Developer', 'TrailerCentral', '2019-06-01 00:00:00.000', '2021-10-01 00:00:00.000', 'Because we couldn''t get our own Facebook Marketplace autoposter working we configured a CSV-based feed instead to send data over to LotVantage, who then used Facebook''s Marketplace feeds to import inventory onto Facebook Marketplace. This worked well for a while until Facebook shutdown the ability for partners to send feed data to Marketplace.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Universal Spritesheet Character Generator', 'Created sprite assets, fixed UI issues, and reworked asset loading from folders and metadata.', 'Web Developer', 'Personal Project', '2024-03-01 00:00:00.000', NULL, 'Supported the Universal Spritesheet Character Generator by creating new sprite assets. Delivered improvements to fix bugs on the interface and rewrite the folder structure to build the layout of assets from the folder structure and json file metadata.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Lex Talionis Engine', 'Added QT folder systems, platform data, autotiles, and mana bar support in Python.', 'Python Development', 'Personal Project', '2025-04-01 00:00:00.000', NULL, 'Contributed to Lex Talionis Engine in Python by implementing new folder systems in QT. Engineered custom platform data and new custom autotiles. Authored new features to MANA system by adding custom mana components and rewriting the health bar data to support mana bars.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Software Engineer III at TrailerCentral', 'Led CRM and marketing initiatives, restored key automations, and shipped Twilio call tracking.', 'Software Engineer III', 'TrailerCentral', '2024-03-01 00:00:00.000', '2026-01-01 00:00:00.000', 'In my role as Systems Engineer III at LeadVenture (TrailerCentral), I led CRM and marketing team initiatives, driving system integrations and enhancing campaign performance. In this phase of my professional career arc, I developed robust backend systems that improved platform functionality, reliability, and user experience, while engineering web scraping solutions to automate data collection and support business intelligence. I also designed and deployed Chrome extensions to streamline workflow efficiency and system interoperability.  Below are my Key Contributions in this role:     • Implemented Twilio-based Click-to-Call functionality and call forwarding on TrailerTrader, restoring Amazon SES campaigns, preventing email bounces, and eliminating repeat account blocks through parallel execution.     • Diagnosed and resolved Craigslist Autoposter and Scheduler failures by redesigning iframe-based payment handling in Laravel Dusk and Chrome Extension, restoring dealer posting capabilities faster than external vendors.     • Architected and deployed a Twilio call-forwarding and lead-tracking system using Laravel, REST APIs, webhooks, XML, queues, and cron jobs, improving call attribution, lead capture, and dealer notification accuracy.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Lead Developer at TrailerCentral', 'Led CRM and marketing teams, migrated the CRM stack, and restored texting reliability.', 'Lead Developer', 'TrailerCentral', '2022-09-01 00:00:00.000', '2024-03-01 00:00:00.000', 'During my tenure as Lead Developer at TrailerCentral, I led the CRM and Marketing teams, driving strategic initiatives, delegating tasks, and performing QA validation to optimize system performance and elevate team efficiency. In this phase of my professional career arc, I enhanced backend systems through web scraping, Chrome extension development, and minor mobile app features to support data operations and streamline user workflows.  Below are my Key Contributions in this role:     • Migrated legacy Zend Framework CRM into modern Nuxt.js/Vue dashboard with Laravel API backend, improving scalability, maintainability, and overall platform performance.     • Preserved Mosaico Email Template Builder functionality during dashboard migration by implementing Nuxt-compatible integration, ensuring uninterrupted campaign and blast operations.     • Restored automated CRM and dealer website texting reliability by implementing Twilio compliance solutions, including dealer-level number verification, opt-in workflows, and delivery status monitoring.     • Spearheaded cross-team hackathon project converting Nuxt.js/Vue dashboard into an Ionic mobile app with full CRM functionality and push notifications, earning second-place recognition for technical execution.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Programmer at TrailerCentral', 'Built automation tools, drafted TrailerTrader, and improved Android camera app stability.', 'Web Programmer', 'TrailerCentral', '2016-03-01 00:00:00.000', '2022-09-01 00:00:00.000', 'As Web Developer at TrailerCentral, I focused on building robust frontend and backend systems to support platform functionality, enhance user experience, and maintain system reliability. In this phase of my professional career arc, I designed and implemented Chrome extensions to streamline workflow automation and improve platform interoperability, while contributing to minor mobile app features to broaden platform accessibility.  Below are my Key Contributions in this role:     • Delivered the first full draft of TrailerTrader, establishing a functional baseline for iterative development and future enhancements.     • Engineered web scraping and automation solutions for Marketing Autoposters on HTW and Craigslist, increasing data collection efficiency and operational throughput.     • Expanded mobile development exposure and improved application stability through incremental enhancements to the Android TrailerCentral Camera App using Java and Android Studio.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at Ponticlaro', 'Delivered freelance web development work for Ponticlaro during a multi-client contract period.', 'Web Developer', 'Ponticlaro', '2013-12-01 00:00:00.000', '2015-09-01 00:00:00.000', 'Worked as a Web Developer for Ponticlaro during an overlapping freelance period. Specific projects retained in this migration were limited, so this entry is kept intentionally broad to reflect the role accurately without over-attributing unrelated project work.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at Lead Optimize', 'Converted legacy websites to WordPress and improved long-term content management.', 'Wordpress Web Developer', 'Lead Optimize', '2012-08-01 00:00:00.000', '2015-01-01 00:00:00.000', 'Delivered client web development work for Lead Optimize, including converting Restyle Kitchen and Bath from an existing ASP website into WordPress so content could be managed more easily over time.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at Appster', 'Built the companion marketing website for the Real Chords mobile app in WordPress.', 'Web Developer', 'Appster', '2011-04-01 00:00:00.000', '2014-03-01 00:00:00.000', 'Worked with Appster on the Real Chords Website, building a PSD-to-WordPress site for the Real Chords mobile app and its companion iPad app. The work included the homepage, manuals, blog page, and media gallery features.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at Millennium Marketing Solutions LLC', 'Delivered site enhancements, contact forms, and new marketing pages.', 'Web Developer', 'Millennium Marketing Solutions LLC', '2012-09-01 00:00:00.000', '2014-02-01 00:00:00.000', 'Supported Millennium Marketing Denver Updates by adding and styling contact forms, building the Connect With Us footer section, updating images and page layouts, and creating the Reputation Marketing and Contact Us pages.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at KloutFire', 'Finalized and maintained multiple client websites across launch and redesign phases.', 'Web Developer', 'KloutFire', '2012-12-01 00:00:00.000', '2013-09-01 00:00:00.000', 'Delivered client work for KloutFire across several websites, including Center for the Partially Sighted, Mangat Plastic Surgery, Tansavatdi Plastic Surgery, and Raffle Consulting. Responsibilities included final launch work, theme fixes, custom layouts, widget-driven navigation, and ongoing content and design updates.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Developer at Yazamo', 'Built and finalized landing pages, press pages, and marketing site updates from provided designs.', 'Web Developer', 'Yazamo', '2013-01-01 00:00:00.000', '2013-08-01 00:00:00.000', 'Supported multiple Yazamo-related projects, including Abundance Campaign landing pages, 25kGroup Magazine Lander, Genius Network Mastermind updates, and the Joe Polish Press Page. Work included PSD-based implementation, page fixes, restyling, and responsive updates.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Development Freelancer at SeoStrong', 'Built PSD-to-WordPress and Flash-to-WordPress sites for several SEO Strong clients.', 'Wordpress Web Developer', 'SeoStrong', '2012-10-01 00:00:00.000', '2013-08-01 00:00:00.000', 'Handled several SEO Strong website projects, including Washington Dental, Express Roofing, Extreme Developers, and BioDental Veneers Landing Page. Work ranged from full PSD-to-WordPress builds to Flash-to-WordPress conversion and complex landing page implementation.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Development Freelancer at Dominate Net', 'Delivered themed WordPress client sites with custom design updates and content setup.', 'Wordpress Web Developer', 'Dominate Net', '2012-11-01 00:00:00.000', '2013-05-01 00:00:00.000', 'Completed Dominate Net client work including the Packard Grill website, where responsibilities included child theme customization, design enhancements, and backend setup of the restaurant menu content.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('Web Application Developer at Freight Access, Inc.', 'Built the original Freight Access CRM in CodeIgniter and established core application architecture.', 'Web Application Developer', 'Freight Access, Inc.', '2010-08-01 00:00:00.000', '2012-10-01 00:00:00.000', 'Created the original Freight Access CRM in CodeIgniter as an early large-scale web application project. The work provided foundational experience in CRM architecture, application workflows, and database-driven development.', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

-- Insert Project Links
INSERT INTO `jr_projects_links` (`project_id`, `website`, `url`, `priority`, `created_at`, `updated_at`)
SELECT p.id, v.website, v.url, 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM (
SELECT 'Sands Investment Group' AS project_name, 'Sands Investment Group' AS website, 'http://signnn.com' AS url
UNION ALL
SELECT 'Real Chords Website' AS project_name, 'Real Chords Website' AS website, 'http://www.realchords.com.au/' AS url
UNION ALL
SELECT 'Millennium Marketing Denver Updates' AS project_name, 'Millennium Marketing Denver Updates' AS website, 'http://www.millenniummarketingdenver.com/' AS url
UNION ALL
SELECT 'Express Roofing, Inc.' AS project_name, 'Express Roofing, Inc.' AS website, 'http://www.expressroofinginc.com/' AS url
UNION ALL
SELECT 'Extreme Developers, Inc.' AS project_name, 'Extreme Developers, Inc.' AS website, 'http://www.extremedevelopersinc.com/' AS url
UNION ALL
SELECT 'Abundance Campaign' AS project_name, 'Abundance Campaign' AS website, 'http://www.abundancethebook.com/ab' AS url
UNION ALL
SELECT 'Packard Grill' AS project_name, 'Packard Grill' AS website, 'http://www.packardgrill.net/' AS url
UNION ALL
SELECT '25kGroup Magazine Lander' AS project_name, '25kGroup Magazine Lander' AS website, 'http://www.25kgroup.com/MySuccess1/' AS url
UNION ALL
SELECT 'BioDental Veneers Landing Page' AS project_name, 'BioDental Veneers Landing Page' AS website, 'http://mybiodental.com/veneers-special' AS url
UNION ALL
SELECT 'Genius Network Mastermind' AS project_name, 'Genius Network Mastermind' AS website, 'http://www.geniusnetworkmastermind.com/25k/' AS url
UNION ALL
SELECT 'Center for the Partially Sighted' AS project_name, 'Center for the Partially Sighted' AS website, 'http://www.low-vision.org/' AS url
UNION ALL
SELECT 'Mangat Plastic Surgery' AS project_name, 'Mangat Plastic Surgery' AS website, 'http://www.mangatplasticsurgery.com' AS url
UNION ALL
SELECT 'Joe Polish Press Page' AS project_name, 'Joe Polish Press Page' AS website, 'http://www.joepolish.com/2012/press' AS url
UNION ALL
SELECT 'Restyle Kitchen and Bath' AS project_name, 'Restyle Kitchen and Bath' AS website, 'http://restylekitchenandbath.com/' AS url
UNION ALL
SELECT 'KloutFire Website' AS project_name, 'KloutFire Website' AS website, 'http://www.kloutfire.com' AS url
UNION ALL
SELECT 'My Choice Energy' AS project_name, 'My Choice Energy' AS website, 'http://www.fostermychoice.com/' AS url
UNION ALL
SELECT 'Tansavatdi Plastic Surgery' AS project_name, 'Tansavatdi Plastic Surgery' AS website, 'http://www.facesbydrt.com' AS url
UNION ALL
SELECT 'Raffle Consulting' AS project_name, 'Raffle Consulting' AS website, 'http://www.raffleconsulting.com' AS url
UNION ALL
SELECT 'Washington Dental' AS project_name, 'Washington Dental' AS website, 'http://www.washington-dental.com/' AS url
UNION ALL
SELECT 'Fort Collins Roofing Consultants' AS project_name, 'Fort Collins Roofing Consultants' AS website, 'http://www.fortcollinsroofingconsultants.com/' AS url
UNION ALL
SELECT 'PeteMamos.com' AS project_name, 'PeteMamos.com' AS website, 'http://www.petemamos.com/' AS url
UNION ALL
SELECT 'Home Solution Properties' AS project_name, 'Home Solution Properties' AS website, 'http://homesolutionproperties.com/' AS url
UNION ALL
SELECT 'Equilibrio Nicaragua' AS project_name, 'Equilibrio Nicaragua' AS website, 'http://www.equilibrionicaragua.com/' AS url
) v
JOIN `jr_projects` p ON p.name = v.project_name;

-- Assign Featured to default project
INSERT INTO `jr_projects_cats` (`project_id`, `category_id`, `priority`, `created_at`, `updated_at`)
SELECT p.id, c.id, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `jr_projects` p
JOIN `jr_cats` c ON c.title = 'Featured Projects'
WHERE p.name = 'JR Programming'
ON DUPLICATE KEY UPDATE `updated_at` = VALUES(`updated_at`);

-- Assign Projects category
INSERT INTO `jr_projects_cats` (`project_id`, `category_id`, `priority`, `created_at`, `updated_at`)
SELECT p.id, c.id, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `jr_projects` p
JOIN `jr_cats` c ON c.title = 'Projects'
WHERE p.position = 'LinkedIn Project'
ON DUPLICATE KEY UPDATE `updated_at` = VALUES(`updated_at`);

-- Assign Work History category
INSERT INTO `jr_projects_cats` (`project_id`, `category_id`, `priority`, `created_at`, `updated_at`)
SELECT p.id, c.id, 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)
FROM `jr_projects` p
JOIN `jr_cats` c ON c.title = 'Work History'
WHERE p.name LIKE '% at %'
ON DUPLICATE KEY UPDATE `updated_at` = VALUES(`updated_at`);